// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx_uCjsNWwLeoQhvIv3rrYA7OOZhStnGY',
    appId: '1:673106653638:web:ce70c58b915590bfa782c7',
    messagingSenderId: '673106653638',
    projectId: 'flutter-chat-app-c2a4a',
    authDomain: 'flutter-chat-app-c2a4a.firebaseapp.com',
    storageBucket: 'flutter-chat-app-c2a4a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2Uyn1vZv91OJ3WMTMae358KiW5763C9M',
    appId: '1:673106653638:android:403ad00988b102cea782c7',
    messagingSenderId: '673106653638',
    projectId: 'flutter-chat-app-c2a4a',
    storageBucket: 'flutter-chat-app-c2a4a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGAczqRy1VhRy8W1dVpIzHUpVsDnEW1Yg',
    appId: '1:673106653638:ios:05670952a732c225a782c7',
    messagingSenderId: '673106653638',
    projectId: 'flutter-chat-app-c2a4a',
    storageBucket: 'flutter-chat-app-c2a4a.appspot.com',
    iosClientId: '673106653638-dsulh4k43gaeo90a3tkg2au86cm9prmv.apps.googleusercontent.com',
    iosBundleId: 'com.adamwinebarger.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGAczqRy1VhRy8W1dVpIzHUpVsDnEW1Yg',
    appId: '1:673106653638:ios:a3fa314f82807191a782c7',
    messagingSenderId: '673106653638',
    projectId: 'flutter-chat-app-c2a4a',
    storageBucket: 'flutter-chat-app-c2a4a.appspot.com',
    iosClientId: '673106653638-cm4rp7pi1mhp93stfb58nq6ocahn726s.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
